project:
  type: website
website:
  title: "MA388 Sabermetrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu:
          - href: lessons/lsn_1_course_intro.qmd
            text: "Lesson 1: Course Introduction"
          - href: lessons/lsn_2_intro_to_R.qmd 
            text: "Lesson 2: Introduction to R"
          - href: lessons/lsn_3_intro_to_R_II.qmd
            text: "Lesson 3: Introduction to R II"
            
      - href: calendar/calendar.qmd
        text: Calendar

format:
  html:
    theme: cosmo
    toc: true

    
execute:
  freeze: auto   # Ensures code is executed during render
