project:
  type: website
website:
  title: "MA388 Sabermetrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu:
          - href: lessons/lsn_1_course_intro.qmd
            text: "Lesson 1: Course Introduction"
          - href: lessons/lsn_2_intro_to_R.qmd 
            text: "Lesson 2: Introduction to R"
          - href: lessons/lsn_3_intro_to_R_II.qmd
            text: "Lesson 3: Introduction to R II"
          - href: lessons/lsn_4_r_graphics_I.qmd
            text: "Lesson 4: R Graphics I"
          - href: lessons/lsn_5_r_graphics_II.qmd
            text: "Lesson 5: R Graphics II"          
          - href: lessons/lsn_6_runs_and_wins_I.qmd
            text: "Lesson 6: Runs and Wins I"
          - href: lessons/lsn_8_runs_and_wins_II.qmd
            text: "Lesson 8: Runs and Wins II"
          - href: lessons/lsn_9_runs_expectancy_matrix.qmd
            text: "Lesson 9: Value of Plays: Run Expectancy Matrix"
          - href: lessons/lsn_10_hits_stealing.qmd
            text: "Lesson 10: Value of Plays: Base Hits and Stealing"
          - href: lessons/lsn_11_swinging_tendencies.qmd
            text: "Lesson 11: Behaviors by Count: Swinging Tendencies"
          - href: lessons/lsn_12_umpire_tendencies.qmd
            text: "Lesson 11: Behaviors by Count: Umpire Tendencies"
      - href: calendar/calendar.qmd
        text: Calendar

format:
  html:
    theme: cosmo
    toc: true

    
execute:
  freeze: auto   # Ensures code is executed during render
