project:
  type: website
website:
  title: "MA388 Sabermetrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lessons.qmd
        text: Lessons
  sidebar:
    style: "floating"
format:
  html:
    theme: cosmo
    toc: true