project:
  type: website
website:
  title: "MA388 Sabermetrics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu:
          - href: lessons/lsn1_course_intro.qmd
            text: "Lesson 1: Course Introduction"
          - href: lessons/lsn2_intro_to_R.Rmd
            text: "Lesson 2: Introduction to R"
  sidebar:
    style: "floating"
format:
  html:
    theme: cosmo
    toc: true